import type { Activity } from "./types";

// ─────────────────────────────────────────────
//  BASE DE DATOS DE ACTIVIDADES — Santiago, Chile
// ─────────────────────────────────────────────

export const ACTIVIDADES: Activity[] = [
  {
    id: "a1",
    nombre: "Parque Metropolitano de Santiago",
    descripcion:
      "El pulmón verde de Santiago. Más de 700 hectáreas con teleférico, zoológico nacional, piscinas, senderos y la Virgen de la Inmaculada Concepción con vistas panorámicas de la ciudad.",
    categoria: "parques",
    imagen: "/images/parque-metro.jpg",
    imagenes: ["/images/parque-metro.jpg", "/images/parque-metro-2.jpg"],
    ubicacion: {
      lat: -33.4299,
      lng: -70.637,
      direccion: "Pío Nono s/n, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "07:00", cierre: "21:00" },
    rating: 4.7,
    totalResenas: 8420,
    afluencia: "media",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy"],
    etiquetas: ["familia", "naturaleza", "gratis", "vista panorámica"],
    duracionMinutos: 180,
  },
  {
    id: "a2",
    nombre: "Cerro San Cristóbal — Sendero Los Pumas",
    descripcion:
      "Ruta de trekking de dificultad media con 4 km de recorrido y 300 m de desnivel. Vistas 360° de Santiago. Ideal para hacer ejercicio y disfrutar la naturaleza dentro de la ciudad.",
    categoria: "aire-libre",
    imagen: "/images/cerro-san-cristobal.jpg",
    ubicacion: {
      lat: -33.4264,
      lng: -70.6213,
      direccion: "Acceso Pío Nono, Cumbre del Cerro San Cristóbal",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 2000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "08:00", cierre: "18:00" },
    rating: 4.8,
    totalResenas: 3210,
    afluencia: "baja",
    enTendencia: true,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy"],
    etiquetas: ["trekking", "ejercicio", "naturaleza", "vistas"],
    duracionMinutos: 120,
  },
  {
    id: "a3",
    nombre: "Mercado Central",
    descripcion:
      "Ícono gastronómico de Santiago. Mariscos y pescados frescos en un edificio patrimonial de hierro forjado del siglo XIX. Los mejores cevicheros y la mítica picada del caldo de mariscos.",
    categoria: "gastronomia",
    imagen: "/images/mercado-central.jpg",
    ubicacion: {
      lat: -33.4373,
      lng: -70.653,
      direccion: "21 de Mayo 1458, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 15000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "09:00", cierre: "22:00" },
    rating: 4.5,
    totalResenas: 12850,
    afluencia: "alta",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog"],
    etiquetas: ["comida", "mariscos", "patrimonio", "turístico"],
    duracionMinutos: 90,
    telefono: "+56 2 2696 8327",
    sitioWeb: "https://www.mercadocentral.cl",
  },
  {
    id: "a4",
    nombre: "Museo Nacional de Bellas Artes",
    descripcion:
      "La colección de arte más importante de Chile. Pintura, escultura y grabado nacional e hispanoamericano desde el siglo XVI hasta el arte contemporáneo. Ingreso gratuito permanente.",
    categoria: "museos",
    imagen: "/images/mnba.jpg",
    ubicacion: {
      lat: -33.4366,
      lng: -70.6502,
      direccion: "José Miguel de la Barra 650, Santiago",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "10:00", cierre: "18:00" },
    rating: 4.6,
    totalResenas: 5670,
    afluencia: "baja",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["arte", "cultura", "gratis", "interior", "patrimonio"],
    duracionMinutos: 90,
    sitioWeb: "https://www.mnba.gob.cl",
  },
  {
    id: "a5",
    nombre: "Estadio Nacional — Clásico Universitario",
    descripcion:
      "Uno de los clásicos más apasionados del fútbol chileno. U de Chile vs U Católica en el Estadio Nacional. Ambiente inigualable en el recinto más icónico del país.",
    categoria: "deportes",
    imagen: "/images/estadio-nacional.jpg",
    ubicacion: {
      lat: -33.4652,
      lng: -70.6095,
      direccion: "Av. Grecia 2001, Ñuñoa",
      comuna: "Ñuñoa",
      ciudad: "Santiago",
    },
    precio: { valor: 12000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "19:00", cierre: "22:00" },
    rating: 4.3,
    totalResenas: 2890,
    afluencia: "alta",
    enTendencia: true,
    cuposDisponibles: false,
    cuposRestantes: 0,
    aptoClima: ["clear", "partly-cloudy", "cloudy"],
    etiquetas: ["fútbol", "deporte", "evento", "agotado"],
    duracionMinutos: 120,
  },
  {
    id: "a6",
    nombre: "Taller de Cerámica Manos de Barro",
    descripcion:
      "Taller íntimo de cerámica en el corazón del Barrio Italia. Grupos de máximo 8 personas. Incluye arcilla, herramientas y primera cocción. Perfecto para parejas y amigos.",
    categoria: "talleres",
    imagen: "/images/taller-ceramica.jpg",
    ubicacion: {
      lat: -33.4444,
      lng: -70.614,
      direccion: "Av. Italia 2345, Barrio Italia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 25000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "10:00", cierre: "19:00" },
    rating: 4.9,
    totalResenas: 880,
    afluencia: "baja",
    enTendencia: true,
    cuposDisponibles: true,
    cuposRestantes: 4,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["artesanía", "creatividad", "pareja", "amigos", "interior"],
    duracionMinutos: 150,
    telefono: "+56 9 8765 4321",
    sitioWeb: "https://www.manosdebarro.cl",
  },
  {
    id: "a7",
    nombre: "Cine Arte Normandie",
    descripcion:
      "El cine arte más querido de Santiago. Programación de cine independiente, clásicos restaurados y festivales internacionales. Café y librería en el lobby.",
    categoria: "cine",
    imagen: "/images/cine-normandie.jpg",
    ubicacion: {
      lat: -33.4448,
      lng: -70.6481,
      direccion: "Tarapacá 1181, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 6500, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "14:00", cierre: "23:30" },
    rating: 4.7,
    totalResenas: 4120,
    afluencia: "media",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: 40,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["cine", "arte", "cultura", "interior", "pareja"],
    duracionMinutos: 120,
    sitioWeb: "https://www.normandie.cl",
  },
  {
    id: "a8",
    nombre: "Tour Gastronómico Barrio Lastarria",
    descripcion:
      "Recorrido guiado de 3 horas por los mejores restaurantes, bares y cafeterías del barrio cultural más bohemio de Santiago. Incluye degustaciones y copa de vino de bienvenida.",
    categoria: "gastronomia",
    imagen: "/images/lastarria.jpg",
    ubicacion: {
      lat: -33.4395,
      lng: -70.6465,
      direccion: "José Victorino Lastarria 90, Barrio Lastarria",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 35000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "12:00", cierre: "20:00" },
    rating: 4.8,
    totalResenas: 1560,
    afluencia: "media",
    enTendencia: true,
    cuposDisponibles: true,
    cuposRestantes: 8,
    aptoClima: ["clear", "partly-cloudy"],
    etiquetas: ["gastronomía", "tour", "vino", "bohemio", "cultura"],
    duracionMinutos: 180,
    telefono: "+56 9 1234 5678",
  },
  {
    id: "a9",
    nombre: "Jardín Botánico Chagual",
    descripcion:
      "Colección viva de más de 1.000 especies de plantas nativas de Chile en 10 hectáreas de paisajismo. Senderos autoguiados, visitas guiadas los fines de semana y café con vista al jardín.",
    categoria: "parques",
    imagen: "/images/chagual.jpg",
    ubicacion: {
      lat: -33.4089,
      lng: -70.5831,
      direccion: "Camino El Observatorio 1155, Vitacura",
      comuna: "Vitacura",
      ciudad: "Santiago",
    },
    precio: { valor: 3000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "09:00", cierre: "18:30" },
    rating: 4.6,
    totalResenas: 2340,
    afluencia: "baja",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy"],
    etiquetas: ["naturaleza", "familia", "fotografía", "plantas nativas"],
    duracionMinutos: 90,
    sitioWeb: "https://www.chagual.cl",
  },
  {
    id: "a10",
    nombre: "Museo Interactivo Mirador (MIM)",
    descripcion:
      "El museo de ciencia y tecnología más grande de América Latina. Más de 300 módulos interactivos, planetario digital y zona de robótica. Ideal para niños, jóvenes y adultos curiosos.",
    categoria: "museos",
    imagen: "/images/mim.jpg",
    ubicacion: {
      lat: -33.4922,
      lng: -70.6519,
      direccion: "Punta Arenas 6711, La Granja",
      comuna: "La Granja",
      ciudad: "Santiago",
    },
    precio: { valor: 4500, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "09:30", cierre: "18:30" },
    rating: 4.5,
    totalResenas: 6780,
    afluencia: "media",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["ciencia", "tecnología", "familia", "niños", "interactivo"],
    duracionMinutos: 150,
    sitioWeb: "https://www.mim.cl",
  },
  {
    id: "a11",
    nombre: "Trekking Cascada de las Ánimas",
    descripcion:
      "Excursión de día completo al Cajón del Maipo. Sendero de 12 km hasta una cascada de 35 metros en plena cordillera. Incluye guía certificado y snack. Dificultad moderada.",
    categoria: "aire-libre",
    imagen: "/images/cascada-animas.jpg",
    ubicacion: {
      lat: -33.7589,
      lng: -70.4247,
      direccion: "Camino al Volcán Km 45, San Alfonso, Cajón del Maipo",
      comuna: "San José de Maipo",
      ciudad: "Región Metropolitana",
    },
    precio: { valor: 8000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "08:00", cierre: "17:00" },
    rating: 4.7,
    totalResenas: 3420,
    afluencia: "baja",
    enTendencia: true,
    cuposDisponibles: true,
    cuposRestantes: 15,
    aptoClima: ["clear", "partly-cloudy"],
    etiquetas: ["trekking", "cascada", "montaña", "naturaleza", "guiado"],
    duracionMinutos: 360,
    telefono: "+56 9 5555 1234",
    sitioWeb: "https://www.cascadadelasanimas.cl",
  },
  {
    id: "a12",
    nombre: "Teatro Municipal — Temporada de Ópera",
    descripcion:
      "Rigoletto de Verdi en el escenario más elegante de Chile. Orquesta Filarmónica, Ballet Estable y elenco internacional. El lujo de la ópera en vivo en el corazón de Santiago.",
    categoria: "teatro",
    imagen: "/images/teatro-municipal.jpg",
    ubicacion: {
      lat: -33.4408,
      lng: -70.6518,
      direccion: "Agustinas 794, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 45000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "20:00", cierre: "23:30" },
    rating: 4.9,
    totalResenas: 9870,
    afluencia: "baja",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: 12,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["ópera", "clásico", "elegante", "cultura", "noche"],
    duracionMinutos: 180,
    sitioWeb: "https://www.municipal.cl",
  },
  {
    id: "a13",
    nombre: "Barrio Yungay — Circuito Patrimonial",
    descripcion:
      "Recorrido autoguiado por el barrio más antiguo y mejor conservado de Santiago. Casonas republicanas, el Museo de la Memoria, la Plaza Yungay y la bodega de La Fábrica.",
    categoria: "museos",
    imagen: "/images/barrio-yungay.jpg",
    ubicacion: {
      lat: -33.4382,
      lng: -70.6705,
      direccion: "Plaza Yungay s/n, Barrio Yungay",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "09:00", cierre: "20:00" },
    rating: 4.5,
    totalResenas: 2100,
    afluencia: "baja",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy"],
    etiquetas: ["patrimonio", "historia", "barrio", "gratis", "fotografía"],
    duracionMinutos: 120,
  },
  {
    id: "a14",
    nombre: "Concierto Jazz — Club de Jazz Santiago",
    descripcion:
      "Noche de jazz en vivo en el club más antiguo de Latinoamérica. Jam sessions los jueves y conciertos de artistas nacionales e internacionales los viernes y sábados.",
    categoria: "musica",
    imagen: "/images/club-jazz.jpg",
    ubicacion: {
      lat: -33.4337,
      lng: -70.6477,
      direccion: "Agustinas 621, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 10000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "20:30", cierre: "01:00" },
    rating: 4.6,
    totalResenas: 3200,
    afluencia: "media",
    enTendencia: true,
    cuposDisponibles: true,
    cuposRestantes: 20,
    aptoClima: ["clear", "partly-cloudy", "cloudy", "rain", "fog", "storm"],
    etiquetas: ["jazz", "música en vivo", "noche", "cultura"],
    duracionMinutos: 150,
    sitioWeb: "https://www.clubdejazz.cl",
  },
  {
    id: "a15",
    nombre: "Feria Artesanal Los Dominicos",
    descripcion:
      "La feria de artesanía más grande y tradicional de Chile. Más de 200 artesanos en un convento colonial del siglo XVIII. Cerámica, platería, textiles y gastronomía regional.",
    categoria: "talleres",
    imagen: "/images/los-dominicos.jpg",
    ubicacion: {
      lat: -33.3985,
      lng: -70.5782,
      direccion: "Av. Apoquindo 9085, Las Condes",
      comuna: "Las Condes",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "10:00", cierre: "20:00" },
    rating: 4.4,
    totalResenas: 5430,
    afluencia: "media",
    enTendencia: false,
    cuposDisponibles: true,
    cuposRestantes: null,
    aptoClima: ["clear", "partly-cloudy", "cloudy"],
    etiquetas: ["artesanía", "souvenir", "compras", "gratis", "familia"],
    duracionMinutos: 120,
  },
];

// ── Helpers ────────────────────────────────────
export function getActividadById(id: string): Activity | undefined {
  return ACTIVIDADES.find((a) => a.id === id);
}

export function getActividades(): Activity[] {
  return ACTIVIDADES;
}

export const CATEGORIAS: [string, string][] = [
  ["cine", "Cine"],
  ["teatro", "Teatro"],
  ["parques", "Parques"],
  ["gastronomia", "Gastronomía"],
  ["museos", "Museos"],
  ["deportes", "Deportes"],
  ["musica", "Música"],
  ["aire-libre", "Aire Libre"],
  ["nightlife", "Nightlife"],
  ["talleres", "Talleres"],
];
