import type { Activity } from "../types";

// Base de actividades para Santiago de Chile
export const ACTIVIDADES: Activity[] = [
  // ── MUSEOS ──────────────────────────────────────────────
  {
    id: "museo-bellas-artes",
    nombre: "Museo Nacional de Bellas Artes",
    descripcion: "El museo más importante de Chile con colecciones de arte chileno e internacional desde el siglo XVI hasta la actualidad.",
    categoria: "museos",
    imagen: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800",
    ubicacion: {
      lat: -33.4372,
      lng: -70.6506,
      direccion: "Parque Forestal s/n, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "10:00", cierre: "19:00", diasSemana: [2,3,4,5,6,0] },
    rating: 4.7,
    totalResenas: 3241,
    afluencia: "media",
    enTendencia: false,
    tags: ["arte", "cultura", "gratuito", "historia"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },
  {
    id: "museo-precolombino",
    nombre: "Museo Chileno de Arte Precolombino",
    descripcion: "Fascinante colección de arte y cultura de los pueblos originarios de América.",
    categoria: "museos",
    imagen: "https://images.unsplash.com/photo-1565799421186-cbf5c02a54c3?w=800",
    ubicacion: {
      lat: -33.4378,
      lng: -70.6522,
      direccion: "Bandera 361, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 4000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "10:00", cierre: "18:00", diasSemana: [2,3,4,5,6,0] },
    rating: 4.8,
    totalResenas: 2180,
    afluencia: "baja",
    enTendencia: true,
    tags: ["arte", "cultura", "historia", "arqueología"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },

  // ── PARQUES ─────────────────────────────────────────────
  {
    id: "parque-metropolitano",
    nombre: "Parque Metropolitano de Santiago",
    descripcion: "El pulmón verde de Santiago con zoológico, piscinas, jardín botánico y las mejores vistas de la ciudad desde el Cerro San Cristóbal.",
    categoria: "parques",
    imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    ubicacion: {
      lat: -33.4214,
      lng: -70.6378,
      direccion: "Pío Nono 450, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "08:00", cierre: "20:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.6,
    totalResenas: 8920,
    afluencia: "alta",
    enTendencia: true,
    tags: ["naturaleza", "familia", "deporte", "vistas", "gratuito"],
    climasCompatibles: ["clear", "partly-cloudy"],
    climasIncompatibles: ["rain", "storm"],
    esBajoTecho: false,
  },
  {
    id: "parque-bicentenario",
    nombre: "Parque Bicentenario",
    descripcion: "Hermoso parque en Vitacura con lagunas artificiales, ciclovías y espacios para picnic junto al río Mapocho.",
    categoria: "parques",
    imagen: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    ubicacion: {
      lat: -33.3957,
      lng: -70.5814,
      direccion: "Av. Bicentenario 4052, Vitacura",
      comuna: "Vitacura",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "07:00", cierre: "21:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.7,
    totalResenas: 5430,
    afluencia: "media",
    enTendencia: false,
    tags: ["naturaleza", "familia", "deporte", "ciclismo", "gratuito"],
    climasCompatibles: ["clear", "partly-cloudy", "cloudy"],
    climasIncompatibles: ["rain", "storm"],
    esBajoTecho: false,
  },

  // ── GASTRONOMÍA ─────────────────────────────────────────
  {
    id: "mercado-central",
    nombre: "Mercado Central",
    descripcion: "Icónico mercado en un bello edificio de hierro decimonónico. El mejor lugar para disfrutar mariscos y pescados frescos de Chile.",
    categoria: "gastronomia",
    imagen: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    ubicacion: {
      lat: -33.4344,
      lng: -70.6508,
      direccion: "San Pablo 967, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 15000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "09:00", cierre: "18:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.4,
    totalResenas: 12300,
    afluencia: "alta",
    enTendencia: true,
    tags: ["comida", "mariscos", "historia", "turismo"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },
  {
    id: "barrio-italia-gastronomia",
    nombre: "Circuito Gastronómico Barrio Italia",
    descripcion: "Recorre los mejores cafés especiales, restaurantes de autor y panaderías artesanales en el bohemio Barrio Italia.",
    categoria: "gastronomia",
    imagen: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    ubicacion: {
      lat: -33.4502,
      lng: -70.6258,
      direccion: "Av. Italia, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 8000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "11:00", cierre: "23:00", diasSemana: [2,3,4,5,6,0] },
    rating: 4.6,
    totalResenas: 3870,
    afluencia: "media",
    enTendencia: true,
    tags: ["café", "brunch", "gastronomía", "barrio"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },

  // ── CINE ────────────────────────────────────────────────
  {
    id: "cine-hoyts-costanera",
    nombre: "Cine Hoyts Costanera Center",
    descripcion: "El complejo de cine más moderno de Santiago con salas 4DX, VIP y la mejor cartelera de estrenos.",
    categoria: "cine",
    imagen: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    ubicacion: {
      lat: -33.4170,
      lng: -70.6069,
      direccion: "Av. Andrés Bello 2447, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 9000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "12:00", cierre: "23:59", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.3,
    totalResenas: 7650,
    afluencia: "alta",
    enTendencia: false,
    tags: ["entretenimiento", "películas", "4DX", "noche"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },
  {
    id: "cine-arte-normandie",
    nombre: "Cine Arte Normandie",
    descripcion: "El cine de culto de Santiago. Programación de arte y ensayo, ciclos temáticos y clásicos del cine mundial.",
    categoria: "cine",
    imagen: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    ubicacion: {
      lat: -33.4477,
      lng: -70.6402,
      direccion: "Tarapacá 1181, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 5500, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "14:00", cierre: "22:00", diasSemana: [2,3,4,5,6,0] },
    rating: 4.8,
    totalResenas: 1820,
    afluencia: "baja",
    enTendencia: false,
    tags: ["cine arte", "cultura", "películas independientes"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },

  // ── TEATRO ──────────────────────────────────────────────
  {
    id: "teatro-municipal",
    nombre: "Teatro Municipal de Santiago",
    descripcion: "El teatro lírico más importante de Chile con temporadas de ópera, ballet y música clásica de nivel internacional.",
    categoria: "teatro",
    imagen: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800",
    ubicacion: {
      lat: -33.4394,
      lng: -70.6487,
      direccion: "Agustinas 794, Santiago Centro",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 25000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "19:00", cierre: "23:00", diasSemana: [3,4,5,6,0] },
    rating: 4.9,
    totalResenas: 4210,
    afluencia: "media",
    enTendencia: true,
    tags: ["ópera", "ballet", "música clásica", "elegante"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },

  // ── DEPORTES ────────────────────────────────────────────
  {
    id: "estadio-san-carlos",
    nombre: "Complejo Deportivo San Carlos de Apoquindo",
    descripcion: "Moderno complejo deportivo con canchas de tenis, pádel, piscina olimpica y clases de fitness.",
    categoria: "deportes",
    imagen: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    ubicacion: {
      lat: -33.4001,
      lng: -70.5553,
      direccion: "Camino Las Flores 13000, Las Condes",
      comuna: "Las Condes",
      ciudad: "Santiago",
    },
    precio: { valor: 12000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "07:00", cierre: "22:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.5,
    totalResenas: 2980,
    afluencia: "media",
    enTendencia: false,
    tags: ["deporte", "fitness", "tenis", "pádel", "piscina"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },
  {
    id: "running-parque-arauco",
    nombre: "Ruta de Running Parque Araucano",
    descripcion: "Recorrido de 5 km por el hermoso Parque Araucano en Las Condes, con circuito iluminado y estaciones de ejercicio.",
    categoria: "deportes",
    imagen: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800",
    ubicacion: {
      lat: -33.3977,
      lng: -70.5858,
      direccion: "Manquehue Norte 1600, Las Condes",
      comuna: "Las Condes",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "06:00", cierre: "21:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.6,
    totalResenas: 1540,
    afluencia: "media",
    enTendencia: false,
    tags: ["running", "gratuito", "naturaleza", "deporte"],
    climasCompatibles: ["clear", "partly-cloudy"],
    climasIncompatibles: ["rain", "storm", "snow"],
    esBajoTecho: false,
  },

  // ── MÚSICA ──────────────────────────────────────────────
  {
    id: "club-de-jazz",
    nombre: "Club de Jazz de Santiago",
    descripcion: "El local de jazz más emblemático de Chile con conciertos en vivo todos los fines de semana.",
    categoria: "musica",
    imagen: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800",
    ubicacion: {
      lat: -33.4249,
      lng: -70.6134,
      direccion: "Av. Italia 1369, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 10000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "20:00", cierre: "02:00", diasSemana: [4,5,6] },
    rating: 4.7,
    totalResenas: 2230,
    afluencia: "alta",
    enTendencia: true,
    tags: ["jazz", "música en vivo", "noche", "copas"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },

  // ── AIRE LIBRE ──────────────────────────────────────────
  {
    id: "cerro-manquehue",
    nombre: "Trekking Cerro Manquehue",
    descripcion: "La caminata icónica de Santiago con 1614 m de altitud. Vista 360° de la ciudad y la cordillera.",
    categoria: "aire-libre",
    imagen: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    ubicacion: {
      lat: -33.3793,
      lng: -70.5421,
      direccion: "Sector Manquehue Alto, Las Condes",
      comuna: "Las Condes",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "07:00", cierre: "17:00", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.8,
    totalResenas: 6780,
    afluencia: "media",
    enTendencia: true,
    tags: ["trekking", "montaña", "naturaleza", "gratuito", "vistas"],
    climasCompatibles: ["clear", "partly-cloudy"],
    climasIncompatibles: ["rain", "storm", "snow", "fog"],
    esBajoTecho: false,
  },
  {
    id: "bicicleta-rio-mapocho",
    nombre: "Ciclovía Río Mapocho",
    descripcion: "Recorre en bicicleta los 42 km de ciclovía junto al río Mapocho cruzando toda la ciudad.",
    categoria: "aire-libre",
    imagen: "https://images.unsplash.com/photo-1558618047-f7abe10cdb83?w=800",
    ubicacion: {
      lat: -33.4289,
      lng: -70.6490,
      direccion: "Ribera Norte Río Mapocho, Santiago",
      comuna: "Santiago",
      ciudad: "Santiago",
    },
    precio: { valor: 0, moneda: "CLP", esPorPersona: false },
    horario: { apertura: "00:00", cierre: "23:59", diasSemana: [0,1,2,3,4,5,6] },
    rating: 4.5,
    totalResenas: 3120,
    afluencia: "media",
    enTendencia: false,
    tags: ["ciclismo", "gratuito", "deporte", "ciudad"],
    climasCompatibles: ["clear", "partly-cloudy", "cloudy"],
    climasIncompatibles: ["rain", "storm"],
    esBajoTecho: false,
  },

  // ── NIGHTLIFE ───────────────────────────────────────────
  {
    id: "bar-loreto",
    nombre: "Bares del Barrio Loreto",
    descripcion: "El barrio de moda de Providencia con los mejores bares, coctelerías y terrazas para salir de noche.",
    categoria: "nightlife",
    imagen: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800",
    ubicacion: {
      lat: -33.4348,
      lng: -70.6162,
      direccion: "Loreto, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 15000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "19:00", cierre: "03:00", diasSemana: [3,4,5,6] },
    rating: 4.5,
    totalResenas: 4870,
    afluencia: "alta",
    enTendencia: true,
    tags: ["bares", "coctelería", "terraza", "noche"],
    climasCompatibles: ["clear", "partly-cloudy"],
    climasIncompatibles: ["rain", "storm"],
    esBajoTecho: false,
  },

  // ── TALLERES ────────────────────────────────────────────
  {
    id: "taller-ceramica",
    nombre: "Taller de Cerámica en Barrio Italia",
    descripcion: "Aprende cerámica con tornos y técnicas de mano en este estudio boutique del Barrio Italia.",
    categoria: "talleres",
    imagen: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800",
    ubicacion: {
      lat: -33.4521,
      lng: -70.6249,
      direccion: "Av. Italia 1840, Providencia",
      comuna: "Providencia",
      ciudad: "Santiago",
    },
    precio: { valor: 22000, moneda: "CLP", esPorPersona: true },
    horario: { apertura: "10:00", cierre: "20:00", diasSemana: [2,3,4,5,6] },
    rating: 4.9,
    totalResenas: 980,
    afluencia: "baja",
    enTendencia: true,
    tags: ["arte", "manualidades", "taller", "creativo"],
    climasCompatibles: [],
    climasIncompatibles: [],
    esBajoTecho: true,
  },
];
